<?php

class check_07 extends KataChecker {

  public $script = "kata_07";
  public $data = [
    [
      'expected' => 'BFKKQJX',
      'params' => [5, 'WAFFLES']
    ],
    [
      'expected' => 'AFCSFT',
      'params' => [1, 'ZEBRES']
    ],
    [
      'expected' => 'FHVDU',
      'params' => [3, 'CESAR']
    ],
    [
      'expected' => 'OEBOVSC',
      'params' => [10, 'EURELIS']
    ],
    [
      'expected' => 'LPVDC',
      'params' => [15, 'WAGON']
    ],
    [
      'expected' => 'ESVQBM',
      'params' => [1, 'DRUPAL']
    ],
  ];

}
