<?php

class check_04 extends KataChecker {

  public $script = "kata_04";
  public $data = [
    [
      'expected' => 0,
      'params' => [0]
    ],
    [
      'expected' => 1,
      'params' => [1]
    ],
    [
      'expected' => 51,
      'params' => [15]
    ],
    [
      'expected' => 2110,
      'params' => [1021]
    ],
    [
      'expected' => 987654321,
      'params' => [123456789]
    ],
  ];

}
